/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#ffb4ab",
        "on-tertiary-fixed-variant": "#004b71",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#ffb4ab",
        "surface-container-low": "#f3f3f3",
        "surface-tint": "#c00014",
        "on-tertiary-fixed": "#001e30",
        "on-secondary-container": "#636262",
        "tertiary-fixed": "#cbe6ff",
        "on-primary-container": "#fffafa",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#e2dfde",
        "on-secondary-fixed-variant": "#474746",
        "on-surface-variant": "#5d3f3c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#93000d",
        "primary-fixed": "#ffdad6",
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "on-surface": "#1a1c1c",
        "outline": "#926f6b",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "primary-container": "#e31e24",
        "tertiary-container": "#007bb5",
        "background": "#f9f9f9",
        "tertiary": "#006190",
        "on-tertiary-container": "#fbfcff",
        "secondary": "#5f5e5e",
        "primary": "#ba0013",
        "surface-container": "#eeeeee",
        "secondary-fixed": "#e5e2e1",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed-dim": "#c8c6c5",
        "on-background": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#e7bdb8",
        "on-primary-fixed": "#410002",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#8ecdff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
