with open(r'e:\ccc\Hotel-manage8\frontend\src\pages\about.css', 'r', encoding='utf-8', errors='ignore') as f:
    lines = f.readlines()

# Prune lines from 672 onwards (0-indexed: 671)
pruned_lines = lines[:671]

with open(r'e:\ccc\Hotel-manage8\frontend\src\pages\about.css', 'w', encoding='utf-8') as f:
    f.writelines(pruned_lines)
    f.write('\n\n/* 6. FINAL CTA BANNER */\n')
    f.write('.features-cta {\n')
    f.write('    padding: 60px 10%;\n')
    f.write('    margin: 80px 0 0 0;\n')
    f.write('    background: linear-gradient(135deg, #d41424 0%, #b40f1d 100%);\n')
    f.write('    color: white;\n')
    f.write('    border-top-left-radius: 60px;\n')
    f.write('    border-top-right-radius: 60px;\n')
    f.write('    text-align: center;\n')
    f.write('    width: 100vw;\n')
    f.write('    position: relative;\n')
    f.write('    left: 50%;\n')
    f.write('    right: 50%;\n')
    f.write('    margin-left: -50vw;\n')
    f.write('    margin-right: -50vw;\n')
    f.write('    overflow: hidden;\n')
    f.write('}\n\n')
    f.write('.features-cta h2 {\n')
    f.write('    font-size: 32px;\n')
    f.write('    font-weight: 850;\n')
    f.write('    margin-bottom: 20px;\n')
    f.write('}\n\n')
    f.write('.features-cta p {\n')
    f.write('    font-size: 18px;\n')
    f.write('    margin: 0 auto 36px;\n')
    f.write('    max-width: 850px;\n')
    f.write('    opacity: 0.95;\n')
    f.write('    line-height: 1.6;\n')
    f.write('}\n\n')
    f.write('.cta-btn {\n')
    f.write('    padding: 16px 48px;\n')
    f.write('    background: white;\n')
    f.write('    color: #d41424;\n')
    f.write('    border-radius: 14px;\n')
    f.write('    font-weight: 800;\n')
    f.write('    border: none;\n')
    f.write('    cursor: pointer;\n')
    f.write('    font-size: 16px;\n')
    f.write('    transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);\n')
    f.write('}\n\n')
    f.write('.cta-btn:hover {\n')
    f.write('    transform: translateY(-5px) scale(1.05);\n')
    f.write('    box-shadow: 0 15px 30px rgba(0, 0, 0, 0.2);\n')
    f.write('}\n\n')
    f.write('@media (max-width: 900px) {\n')
    f.write('    .features-cta h2 { font-size: 24px; }\n')
    f.write('    .features-cta p { font-size: 14px; }\n')
    f.write('    .features-cta { padding: 40px 5%; border-radius: 40px 40px 0 0; }\n')
    f.write('}\n')
